"""empty message

Revision ID: 3dd9fcc94817
Revises: 56ce248ff1e3
Create Date: 2015-08-23 14:42:30.978347

"""

# revision identifiers, used by Alembic.
revision = '3dd9fcc94817'
down_revision = '56ce248ff1e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('status', sa.SmallInteger(),  server_default=0))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'status')
    ### end Alembic commands ###
