"""empty message

Revision ID: 56ce248ff1e3
Revises: None
Create Date: 2015-08-23 14:41:23.764440

"""

# revision identifiers, used by Alembic.
revision = '56ce248ff1e3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
